# Generated by Django 4.2.4 on 2023-09-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta1', models.CharField(choices=[('verdadero', 'Verdadero'), ('falso', 'Falso'), ('nulo', 'Nulo')], default='nulo', max_length=10)),
                ('Pregunta2', models.CharField(choices=[('verdadero', 'Verdadero'), ('falso', 'Falso'), ('nulo', 'Nulo')], default='nulo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevistados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('hombre', models.BooleanField(default=False)),
                ('mujer', models.BooleanField(default=False)),
            ],
        ),
    ]
